export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  LISTINGS: '/listings',
  LISTING_DETAIL: (id: string) => `/listings/${id}`,
  FAVORITES: '/favorites',
  CHAT: '/chat',
  CHAT_ROOM: (id: string) => `/chat/${id}`,
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  MY_LISTINGS: '/my-listings',
  NEW_LISTING: '/my-listings/new',
  EDIT_LISTING: (id: string) => `/my-listings/${id}/edit`,
  PREMIUM: '/premium',
  ADMIN_DASHBOARD: '/dashboard',
  ADMIN_USERS: '/dashboard/users',
  ADMIN_LISTINGS: '/dashboard/listings',
  ADMIN_PREMIUM: '/dashboard/premium',
} as const;
